
version: "3"
services:
  app:
    container_name: client
    build:
      dockerfile: client/Dockerfile
    ports:
      - ${CLIENT_PORT}:4200
    networks:
      - main
  server:
    container_name: server
    build:
      dockerfile: server/Dockerfile
    ports:
      - ${SERVER_PORT}:4000
    networks:
      - main
    depends_on:
      - mongo
  mongo:
    container_name: database_mongo
    image: mongo:latest
    volumes:
      - ./mongo/dump:/dump
      - ./mongo/script.sh:/docker-entrypoint-initdb.d/script.sh
    # command: mongorestore /var/dump, amb el "docker-entrypoint.... ja executa l'script"
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - main
networks:
  main:
    driver: bridge
    external: true

